# Generated by Django 4.0 on 2023-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('short_name', models.CharField(max_length=100)),
                ('phenotype_name', models.CharField(max_length=100)),
                ('mesh_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'disease_info',
            },
        ),
    ]
