# Generated by Django 4.0 on 2023-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('amplicon_16s', models.CharField(max_length=100)),
                ('amplicon_ITS', models.CharField(max_length=100)),
                ('WGS', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
