# Generated by Django 4.1 on 2023-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Searchable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=100)),
                ("accession", models.CharField(max_length=100)),
            ],
            options={"db_table": "searchable",},
        ),
    ]
