# Generated by Django 4.1 on 2023-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_searchable"),
    ]

    operations = [
        migrations.CreateModel(
            name="taxa2ncbi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgmt_micro_id", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=100)),
                ("taxa", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("taxid", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(max_length=100)),
            ],
        ),
    ]
