# Generated by Django 4.0 on 2023-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='WGS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='amplicon_16s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='amplicon_ITS',
            field=models.IntegerField(),
        ),
    ]
