# Generated by Django 4.0 on 2023-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_wgs_alter_project_amplicon_16s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('amplicon_16s', models.IntegerField()),
                ('amplicon_ITS', models.IntegerField()),
                ('WGS', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
            options={
                'db_table': 'run',
            },
        ),
    ]
