# Generated by Django 4.1 on 2023-08-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_taxa2ncbi"),
    ]

    operations = [
        migrations.AlterModelTable(name="taxa2ncbi", table="taxa2ncbi",),
    ]
