# Generated by Django 4.1 on 2023-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_taxa2ncbi_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxa2ncbi",
            name="hgmt_micro_id",
            field=models.CharField(max_length=300),
        ),
    ]
