# Generated by Django 4.0 on 2023-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_id', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('taxa', models.CharField(max_length=100)),
                ('kingdom', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('w_statistic', models.FloatField()),
                ('p_value', models.FloatField()),
                ('lfc', models.FloatField()),
                ('assay_type', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('control', models.CharField(max_length=100)),
                ('num_case', models.IntegerField()),
                ('num_control', models.IntegerField()),
                ('taxa_short_name', models.CharField(max_length=100)),
                ('display', models.BooleanField()),
            ],
            options={
                'db_table': 'da_results',
            },
        ),
    ]
