# Generated by Django 4.0 on 2023-05-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_daresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daresults',
            old_name='case',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='daresults',
            old_name='control',
            new_name='control_name',
        ),
        migrations.RenameField(
            model_name='daresults',
            old_name='level',
            new_name='taxon_level',
        ),
    ]
