# Generated by Django 4.0 on 2023-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_daresults_taxa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.CharField(max_length=500)),
                ('run_id', models.CharField(max_length=100)),
                ('abundance', models.FloatField()),
            ],
            options={
                'db_table': 'feature_table',
            },
        ),
    ]
