# Generated by Django 4.1 on 2023-08-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_taxa2ncbi_scientific_name"),
    ]

    operations = [
        migrations.DeleteModel(name="FeatureTable",),
    ]
