# Generated by Django 4.1 on 2023-08-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_delete_featuretable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureTableBac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxa", models.CharField(max_length=500)),
                ("run_id", models.CharField(max_length=100)),
                ("abundance", models.FloatField()),
            ],
            options={"db_table": "feature_table_bac",},
        ),
        migrations.CreateModel(
            name="FeatureTableFungi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxa", models.CharField(max_length=500)),
                ("run_id", models.CharField(max_length=100)),
                ("abundance", models.FloatField()),
            ],
            options={"db_table": "feature_table_fungi",},
        ),
    ]
