# Generated by Django 4.0 on 2023-05-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_featuretable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('assay_type', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=100)),
                ('public_accession', models.CharField(max_length=100, null=True)),
                ('journal', models.CharField(max_length=100, null=True)),
                ('handler', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'project_all',
            },
        ),
    ]
