# Generated by Django 4.0 on 2023-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_projectall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectall',
            name='project_description',
            field=models.CharField(max_length=500),
        ),
    ]
