# Generated by Django 4.2.17 on 2024-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_featuretablebac_featuretablefungi'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa2ncbi',
            name='assay_type',
            field=models.CharField(default='U', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxa2ncbi',
            name='scientific_short_name',
            field=models.CharField(default='U', max_length=100),
            preserve_default=False,
        ),
    ]
