# Generated by Django 4.0 on 2023-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_projectall_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectall',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
