# Generated by Django 4.2.17 on 2024-12-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_qc_bacteria_gg_samplemetacurated_qc_kos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetacurated',
            name='sample_description',
            field=models.CharField(max_length=200),
        ),
    ]
