# Generated by Django 4.2.17 on 2024-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_samplemetacurated_sample_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTableKOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko', models.CharField(max_length=500)),
                ('run_id', models.CharField(max_length=100)),
                ('abundance', models.FloatField()),
            ],
            options={
                'db_table': 'feature_table_kos',
            },
        ),
        migrations.CreateModel(
            name='GMTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('nproject', models.IntegerField()),
            ],
            options={
                'db_table': 'gmtd',
            },
        ),
        migrations.CreateModel(
            name='GMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('nproject', models.IntegerField()),
            ],
            options={
                'db_table': 'gmtp',
            },
        ),
    ]
