# Generated by Django 4.0 on 2023-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectall_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectall',
            name='project_description',
            field=models.CharField(max_length=3000),
        ),
    ]
