# Generated by Django 4.2.17 on 2024-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_featuretablekos_gmtd_gmtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='daresults',
            name='scientific_name',
            field=models.CharField(default='0', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daresults',
            name='scientific_short_name',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daresults',
            name='taxon_id',
            field=models.CharField(default='0', max_length=15),
            preserve_default=False,
        ),
    ]
