# Generated by Django 4.2.17 on 2024-12-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_daresults_scientific_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmtd',
            old_name='case',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='gmtp',
            old_name='case',
            new_name='case_name',
        ),
    ]
