# Generated by Django 4.0 on 2023-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_projectall_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('associated_project', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'project_summary',
            },
        ),
    ]
