# Generated by Django 4.2.17 on 2024-12-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_case_gmtd_case_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmtd',
            old_name='case_name',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='gmtp',
            old_name='case_name',
            new_name='case',
        ),
    ]
