# Generated by Django 4.0 on 2023-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_projectsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsummary',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
