# Generated by Django 4.0 on 2023-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_projectsummary_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMetaCurated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('run_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('assay_type', models.CharField(max_length=100)),
                ('sequencing_method', models.CharField(max_length=100)),
                ('phenotype_name', models.CharField(max_length=100)),
                ('sample_description', models.CharField(max_length=100)),
                ('phenotype_id', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('geographic_location', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('lattitude', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('bmi', models.FloatField()),
                ('antibiotic_use', models.CharField(max_length=100)),
                ('antibiotic_name', models.CharField(max_length=100)),
                ('bodysite', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('batch2', models.CharField(max_length=100)),
            ],
        ),
    ]
