# Generated by Django 4.0 on 2023-05-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_samplemetacurated'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='samplemetacurated',
            table='sample_meta_curated',
        ),
    ]
