# Generated by Django 4.0 on 2023-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_samplemetacurated_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetacurated',
            name='bmi',
            field=models.CharField(max_length=100),
        ),
    ]
